/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.jandana.interfazdinamica.gui;

import cl.jandana.interfazdinamica.logica.Logica;
import cl.jandana.interfazdinamica.logica.Matriz;

/**
 *
 * @author Javier
 */
public class Gui extends javax.swing.JFrame {

    private final int columnas = 40;
    private final int filas = 40;
    private static Logica logica;
    private static Matriz matriz;

    public Gui() {
        initComponents();
        matriz = new Matriz(columnas, filas);
        //muestra el panel
        panelDinamico1.getImagen();
        logica = new Logica(matriz, panelDinamico1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDinamico1 = new cl.jandana.interfazdinamica.util.PanelDinamico();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelDinamico1Layout = new javax.swing.GroupLayout(panelDinamico1);
        panelDinamico1.setLayout(panelDinamico1Layout);
        panelDinamico1Layout.setHorizontalGroup(
            panelDinamico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        panelDinamico1Layout.setVerticalGroup(
            panelDinamico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDinamico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDinamico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Gui theApp = new Gui();
        theApp.show();
        logica.stop();
        logica.start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cl.jandana.interfazdinamica.util.PanelDinamico panelDinamico1;
    // End of variables declaration//GEN-END:variables
}
